MATRIX_SRC_DIR=matrix
MATRIX_NAIVE_SRC=matrix_naive.py
MATRIX_NAIVE_CL_SRC=naive_implementation.cl

OUT_DIR=../output

matrix-naive-graphs:
	cp $(MATRIX_SRC_DIR)/$(MATRIX_NAIVE_SRC) \
		$(MATRIX_SRC_DIR)/$(MATRIX_NAIVE_CL_SRC) $(OUT_DIR)
