MATRIX_SRC_DIR=matrix
MATRIX_MAIN_SRC=main.py
MATRIX_CLASS_SRC=matrixmultiplication.py

OUT_DIR=../output

matrix-graphs:
	cp $(MATRIX_SRC_DIR)/$(MATRIX_CLASS_SRC) \
		$(MATRIX_SRC_DIR)/$(MATRIX_MAIN_SRC) \
		$(MATRIX_SRC_DIR)/*.cl $(OUT_DIR)
